# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
cache: packages

r:
 - oldrel
 - release
 # - devel

r_github_packages:
 - sjmgarnier/viridis

after_success:
  - Rscript -e 'covr::codecov()'
